import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/core/index.ts",
    "src/http/index.ts",
    "src/foundation/index.ts",
    "src/auth/index.ts",
    "src/orm/index.ts",
    "src/db/index.ts",
    "src/validation/index.ts",
    "src/events/index.ts",
    "src/session/index.ts",
    "src/log/index.ts",
    "src/cache/index.ts",
    "src/queue/index.ts",
    "src/mail/index.ts",
    "src/storage/index.ts",
    "src/bridge/index.ts",
    "src/resilience/index.ts",
    "src/scheduler/index.ts",
    "src/flags/index.ts",
    "src/notifications/index.ts",
    "src/tenancy/index.ts",
    "src/i18n/index.ts",
    "src/ui/index.ts",
    "src/helpers/index.ts",
    "src/http-client/index.ts",
    "src/media/index.ts",
    "src/encrypt/index.ts",
    "src/crypto/index.ts",
    "src/number/index.ts",
    "src/pipeline/index.ts",
    "src/testing/index.ts",
    "src/faker/index.ts"
  ],
  format: ["esm"],
  splitting: true,
  treeshake: true,
  dts: true,
  sourcemap: true,
  clean: true
});
