import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'index':              'src/index.ts',
    'core/index':         '../core/src/index.ts',
    'http/index':         '../http/src/index.ts',
    'foundation/index':   '../foundation/src/index.ts',
    'auth/index':         '../auth/src/index.ts',
    'orm/index':          '../orm/src/index.ts',
    'validation/index':   '../validation/src/index.ts',
    'events/index':       '../events/src/index.ts',
    'session/index':      '../session/src/index.ts',
    'log/index':          '../log/src/index.ts',
    'cache/index':        '../cache/src/index.ts',
    'queue/index':        '../queue/src/index.ts',
    'mail/index':         '../mail/src/index.ts',
    'storage/index':      '../storage/src/index.ts',
    'bridge/index':       '../bridge/src/index.ts',
    'resilience/index':   '../resilience/src/index.ts',
    'scheduler/index':    '../scheduler/src/index.ts',
    'flags/index':        '../flags/src/index.ts',
    'notifications/index':'../notifications/src/index.ts',
    'tenancy/index':      '../tenancy/src/index.ts',
    'i18n/index':         '../i18n/src/index.ts',
    'ui/index':           '../ui/src/index.ts',
    'helpers/index':      '../helpers/src/index.ts',
    'http-client/index':  '../http-client/src/index.ts',
    'media/index':        '../media/src/index.ts',
    'testing/index':      '../testing/src/index.ts',
    'faker/index':        '../faker/src/index.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: [],
})
